### ISSUE TITLE
License placement?

### ISSUE THREAD

**Issue by bryanhelmig** [gabrielfalcao/HTTPretty#11]
Seems rather odd to have the license in each and every file. Most Python libs & GitHub repos just place them in a root level `LICENSE` and keep source clean.

Just thought I'd ask, definitely a minor thing.

**Comment by evinism** [comment]
hahah, I'm gonna open a PR for this. W/ github's nice ui for licenses, a separate license file makes sense to me, and I'll see what maintainers think.

**Comment by evinism** [comment]
actually i'm dumb-- it's under COPYING
