### ISSUE TITLE
On OS X, HTTPretty prevents normal connections when enabled

### ISSUE THREAD

**Issue by larsks** [gabrielfalcao/HTTPretty#164]
Under Linux, this works fine:

    >>> import httpretty
    >>> import requests
    >>> requests.get('http://google.com/')
    <Response [200]>

But under OS X (`uname -r` == `13.1.0`), the `requests.get(...)` call
hangs indefinitely.  This is with Python 2.7.x on both platforms.

**Comment by gabrielfalcao** [comment]
This might have been fixed by @frankamp on #216
