### ISSUE TITLE
Enabling httpretty kills Redis client

### ISSUE THREAD

**Issue by LotharSee** [gabrielfalcao/HTTPretty#194]
Hi,

Redis is a key-value store with a non-HTTP protocol, and it's python client `redis-py` use `socket` to work.
However, enabling HTTPretty makes any Redis command hanging forever.

Here is an easy script to reproduce it (you don't even need to have Redis installed to see the difference).
```
import redis
import httpretty

httpretty.enable()

redis.Redis().ping()
# Will hang forever if httpretty is enabled, will return True or an error otherwise
```

It could be solved by enabling/disabling httpretty every time I don't need it / I use a socket for something else, but it would require to put that everywhere and violate the encapsulation.

And more generally, I wouldn't expect HTTPretty to break requests that I didn't register for, and more especially when they aren't HTTP.

Any thoughts about that? Would it be technically hard to fix? (I can help).

**Comment by gabrielfalcao** [comment]
This might have been fixed by @frankamp on #216
