### ISSUE TITLE
UnicodeDecodeError in tox install if LC_ALL = C

### ISSUE THREAD

**Issue by smoser** [gabrielfalcao/HTTPretty#223]
if LC_ALL is 'C', then installation in a tox environment fails.
Removing the 'setenv' block allows it to work.

    $ cat tox.ini
    [tox]
    envlist = py34
    recreate = True
    
    [testenv]
    commands = python -c 'import sys; sys.exit(0)'
    deps =
        httpretty
    setenv =
        LC_ALL = C

    $ cat setup.py
    from distutils.core import setup
    setup(
        name="MyApplication", version="0.1.0",
        author="foo", author_email="foo@example.com",
    )

    $ rm -Rf .tox; tox -c tox.ini  -v
    ...
    Downloading/unpacking httpretty
      Running setup.py (path:/tmp/pip-build-t5a7ox6l/httpretty/setup.py) egg_info for package httpretty
        Traceback (most recent call last):
          File "<string>", line 17, in <module>
          File "/tmp/pip-build-t5a7ox6l/httpretty/setup.py", line 86, in <module>
            version=read_version(),
          File "/tmp/pip-build-t5a7ox6l/httpretty/setup.py", line 46, in read_version
            finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
          File "/tmp/pip-build-t5a7ox6l/httpretty/setup.py", line 78, in <lambda>
            open(os.path.join(os.path.dirname(__file__), *f)).read()
          File "/tmp/my/.tox/py34/lib/python3.4/encodings/ascii.py", line 26, in decode
            return codecs.ascii_decode(input, self.errors)[0]
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-t5a7ox6l/httpretty/setup.py", line 86, in <module>
        version=read_version(),
      File "/tmp/pip-build-t5a7ox6l/httpretty/setup.py", line 46, in read_version
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
      File "/tmp/pip-build-t5a7ox6l/httpretty/setup.py", line 78, in <lambda>
        open(os.path.join(os.path.dirname(__file__), *f)).read()
      File "/tmp/my/.tox/py34/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)

**Comment by smoser** [comment]
It seems that this appeared in 0.8.1 (using deps of 'httpretty==0.8.0' passes, but 'httpretty==0.8.1' fails).

**Comment by smoser** [comment]
seems likely to be related to https://github.com/gabrielfalcao/HTTPretty/commit/42b24768100c5dd4f23b84fe1e8e742d840d14ab and the unicde seen there in readme.rst

**Comment by syndbg** [comment]
Just tested it with `0.8.8`. It's fixed :+1:

**Comment by smoser** [comment]
Well, the original test case that I opened with above is still failing.
see http://paste.ubuntu.com/10679735/ .
Note, this is python3 that fails. python2 does not.
Also recreates with
 LANG=C pip3 install --root=./x httpretty

dies with:
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

**Comment by Tarrasch** [comment]
Did you find any workaround @smoser?

**Comment by smoser** [comment]
The easiest work around is to just install with a utf-8 locale. (en_US.utf-8)

**Comment by Tarrasch** [comment]
Thanks @smoser! Do you happen to know if the locale for the Travis build environment suddenly changed since yesterday? Or is only spotify/luigi affected by this?

**Comment by smoser** [comment]
On Wed, 13 May 2015, Arash Rouhani wrote:

> Thanks @smoser! Do you happen to know if the locale for the Travis build environment suddenly changed since yesterday? Or is only spotify/luigi affected by this?

I don't know.
I just fixed my tox environment by adding 'LC_ALL' to the setenv.

old:
  setenv = VIRTUAL_ENV={envdir}

new:
  setenv = VIRTUAL_ENV={envdir}
    LC_ALL = en_US.utf-8

**Comment by ReAzem** [comment]
Same issue [here](http://logs.openstack.org/10/183210/4/check/gate-surveil-python34/0494518/console.html)
