### ISSUE TITLE
Resource Warning in v.0.8.7 make test runners hanging forever [Python 3.4.1]

### ISSUE THREAD

**Issue by quasipedia** [gabrielfalcao/HTTPretty#228]
On upgrading my system from v.0.8.3 to the latest v.0.8.7, I noticed that in python3 my test suite (ran by `nose`) hung forever.  I tried to run it with `py.test` but the same happened again.

Finally, by trying with `python -m unittest` I was able to see this output:

```
/usr/lib64/python3.4/unittest/mock.py:1795: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=<httpretty.core.fakesock.socket object at 0x7f52eb824ef0>, proto=6, laddr=('0.0.0.0', 0)>
  setattr(_type, entry, MagicProxy(entry, self))
```

The problem only shows with Python 3.4.1, not with Python 2.7.8.

Example test triggering the warning:

```
@httpretty.activate
def test_put_ko(self):
    response_body = {'error': 'WTF!'}
    httpretty.register_uri(httpretty.PUT, self.url,
                           status=400,
                           body=json.dumps(response_body),
                           content_type='text/json')
    ...
```

**Comment by dmkc** [comment]
I'm experiencing this when using the moto library: https://github.com/spulec/moto/issues/318 Locking the lib down to 0.8.6 fixes thangs

**Comment by nikmolnar** [comment]
I've encountered this as well. I noticed it when my travis builds started timing out. Python 2.7.9 works fine, Python 3.4.2.
