### ISSUE TITLE
fake socket has wrong keyword argument protocol instead of proto

### ISSUE THREAD

**Issue by sk-** [gabrielfalcao/HTTPretty#250]
The signature of `socket` is `socket(family=AF_INET, type=SOCK_STREAM, proto=0, fileno=None)` as described in https://docs.python.org/3.4/library/socket.html#functions. However, `fakesocket` signature is 
`socket(family=AF_INET, type=SOCK_STREAM, protocol=0)`.

This means that any call using the keyword argument `proto` will fail.

This was detected in the context of trying to use `aiohttp` with `HTTPretty`.

**Comment by skygeo** [comment]
Hi @sk- 

Would this do the trick?
https://github.com/skygeo/HTTPretty/commit/ff90dbd4bde1403a9223aaad9b0d2ffb38947255

**Comment by mbatchkarov** [comment]
Any updates on this two years later? Is HTTPretty being maintained?

**Comment by mindflayer** [comment]
I am the author of a module which works with the same principles used by httpretty and supports `asyncio`. I only need help to fix it for HTTPS. Have a look if you are interested in mocking the socket when using asyncio based libraries.
https://github.com/mindflayer/python-mocket

**Comment by mindflayer** [comment]
Just fixed the problem with HTTPS. Here is the new version of `mocket`: https://pypi.python.org/pypi/mocket/2.0.0

**Comment by eirikur-grid** [comment]
OK, just had a test fail after having added code that implicitly performs async socket IO. Traced it down to the proto vs protocol argument naming mismatch. Perplexed that this is still not fixed 4 years after having been reported.

**Comment by mindflayer** [comment]
@eirikur-grid try `mocket` and let me know if you need help.
