### ISSUE TITLE
support for python 3.5

### ISSUE THREAD

**Issue by anupamme** [gabrielfalcao/HTTPretty#269]
Hello,

I am not able to install httpretty on ubuntu for python 3.5.

output of uname -a:
Linux instance-8 4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I downloaded the repo and tried running tests
python3.5 setup.py test
output:
Traceback (most recent call last):
  File "setup.py", line 60, in parse_requirements
    requirements = [req.strip() for req in local_file(path).splitlines()]
  File "setup.py", line 81, in <lambda>
    os.path.join(os.path.dirname(**file**), *f), encoding='utf-8').read()
FileNotFoundError: [Errno 2] No such file or directory: 'test-requirements.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 97, in <module>
    tests_require=parse_requirements('test-requirements.txt'),
  File "setup.py", line 62, in parse_requirements
    raise RuntimeError("Couldn't find the `requirements/use.txt' file :(")
RuntimeError: Couldn't find the`requirements/use.txt' file :(

Although this file is present and permissions are also adequate.

Let me know if you guys know how to fix this.

**Comment by afgane** [comment]
+1

**Comment by ze-phyr-us** [comment]
This is not specific to Python 3.5. I can't install httpretty==0.8.11 on Python 3.4 either. It seems .11 is still broken despite some recent commits that apparently aim to fix it.

`pip install httpretty==0.8.10` works without any issues.

**Comment by anupamme** [comment]
thats correct: 0.8.10 works without any issues.

so, closing this issue

**Comment by afgane** [comment]
Sorry but I don't understand the logic here behind closing the issue: at least three people have confirmed v0.8.11 does not install. The fact 0.8.10 works is not a resolution - it's a workaround. One of the libraries I'm using has a dependency that's stated as `httpretty>=0.6.0` and Travis (and users) hence install the latest available version, which does not work. The fact 0.8.10 works is hardly any help here.

**Comment by anupamme** [comment]
ok my bad. re-opening it.
