### ISSUE TITLE
is HTTPretty "upstream" dead? 

### ISSUE THREAD

**Issue by yarikoptic** [gabrielfalcao/HTTPretty#272]
started to use HTTPretty for one of the projects but immediately ran into side-effects of it while testing on travis with python 3.4.2... from activity in the bug tracker and pull requests got impression that unfortunately  @gabrielfalcao seems to have no more of interest/free time to push it forward. So for myself I see two possible ways 

1. immediately stop using it
2. help to maintain it

in case of 2 I see

2.1. @gabrielfalcao brings more developers on board (I could help from time to time) so outstanding PRs and issues are slowly getting dealt with
2.2. we fork it into e.g. HTTPrettiest ;)
2.3. (meld of 2.2 and 2.1) @gabrielfalcao blesses us to fork it while keeping its name

I would prefer 2.1.  For any of 2. it would work if there is more people with interest and expertise to join.

**Comment by KarelJakubec** [comment]
Hi,
there is another issue about this https://github.com/gabrielfalcao/HTTPretty/issues/213. And yes, it seems to be dead. :(

I tried to reach @gabrielfalcao with both github and email asking him to add some collaborators, but I got no answer and so far I haven't any other way to reach him. I would definitely prefer 2.1., but 2.2. is imho the only option provided @gabrielfalcao is not interested anymore and we won't get his blessing to continue under HTTPretty. Anyway if somebody does the fork, I will try to help to maintain it. I have already few patches in my own private fork.

**Comment by yarikoptic** [comment]
I still really hope that @gabrielfalcao will come back.  meanwhile just to facilitate some actions I have 
- cloned this repo into  https://github.com/HTTPretty/HTTPretty, enabled Travis for it
- added @gabrielfalcao  and @KarelJakubec to developers
- merged following PR which I quickly thought worth getting without fearing breakages: #256
- travis still doesn't see this organization among mine, although I have made my membership public... will try tomorrow
- #193 is the one I also ran into, which was fixed after the last release of the httpretty (0.8.3) so we need to aim for a new release
- I still hope that @gabrielfalcao would reply (will drop him one more email) at least briefly so we know how to proceed -- keep the name/location or fully fork/rename, so we could aim for 0.8.4 release asap

Cheers!

**Comment by yarikoptic** [comment]
actually I got mislead somewhat by missing tags -- git repo has only 0.8.3 as the latest athough 0.8.10 release from this May is on pypi... so #193 fix was released I assume

**Comment by EliRibble** [comment]
You may want to enable issues on the new repo - I was looking for a way to start writing some stuff around what I'm experiencing and found Issues are turned off

**Comment by yarikoptic** [comment]
Thanks @EliRibble ... not sure how I have managed to miss it -- enabled now

**Comment by BenjamenMeyer** [comment]
@yarikoptic thanks, re-parented my fork to the org...just wish Github had better support for doing so

**Comment by gabrielfalcao** [comment]
Hey all, I'm sorry for being away for so long. I never lost interest in HTTPretty it was just a complete lack of time management + life problems.

I just did:

* fixed all the tests
* using nose-randomly by default to find inter-dependent tests (and found lots of issues)
* migrated the docs to sphinx and [hosted it](http://httpretty.readthedocs.org/en/latest/) at read the docs.

**Comment by yarikoptic** [comment]
Hi @gabrielfalcao , great to see you back!  So what do you think about making httpretty team maintained?  may be even moving under 'httpretty/httpretty' ?

meanwhile I will leave few questions on your fresh commits

**Comment by yarikoptic** [comment]
@gabrielfalcao , could you push tags for recent releases?

**Comment by gabrielfalcao** [comment]
@yarikoptic just tagged 0.8.10 and 0.8.11

**Comment by yarikoptic** [comment]
great. Thanks!  
So what about compatibility with 3.4?  setup.py still claims having it (which is logical) but .travis.yml got it excluded with this 0.8.11 release.

**Comment by grahamc** [comment]
@gabrielfalcao Can you please relinquish control of HTTPretty? Not having sufficient python3 support is a real mess, and having a historically unresponsive maintainer on a top pypi project is very frustrating.

**Comment by gabrielfalcao** [comment]
@grahamc happy new year to you.
First of all, I find a bit heavy to say "relinquish control", HTTPretty is open source and anyone can send pull requests, I do have a few contributors that have direct push access.

If you are willing to work in order to deserve push access, you can simply send a pull request with the feature that you want to implement (python 3 support, perhaps?) and if your code has a good test coverage and code quality I will be more than happy to work on giving you push access.

**Comment by grahamc** [comment]
Here are some PRs I sent you last April:

 - https://github.com/gabrielfalcao/couleur/pull/10
 - https://github.com/gabrielfalcao/HTTPretty/pull/255
 - https://github.com/gabrielfalcao/HTTPretty/pull/256
 - https://github.com/gabrielfalcao/markment/pull/4 (this one, I believe, fails due to couleur's issues)

Here is a new one: https://github.com/gabrielfalcao/HTTPretty/pull/281

**Comment by gabrielfalcao** [comment]
@grahamc  I'm sorry for not being able to answer your PR's timely.
I'm checking them right now, here is a follow up:

#255 is obsolete, I fixed the requirements in Dec 2015.
#256 is a great PR, and I'm very sorry for not seeing it before.

gabrielfalcao/markment was a pet project that I decided to abandon because I gave up on using markdown, HTTPretty now [uses](https://github.com/gabrielfalcao/HTTPretty/blob/master/Makefile#L52) sphinx instead.

I'm merging #281 despite your passive-aggressive tone.

Thank you

**Comment by grahamc** [comment]
Thank you for reviewing my PRs now. I'm glad to hear HTTPretty is using Sphinx now, there was a long chain of python2-only code I was trying to resolve last April to bring all the subsequent dependencies up to python3.

I apologize for the my aggressive tone. Last April I did quite a bit of work to make it python3 official (more than the PRs than I put in,) and was very frustrated to have the work met with radio silence.

Best,
Graham

**Comment by gabrielfalcao** [comment]
Like I said, I'm very sorry for not seeing your PR's before. Creating, maintaining and contributing to open source projects require a lot of patience, as you know, from both sides.
I just want you to know that I respect the time taken by all the contributors and I wish I could answer PR's more often.
As a new year's resolution I'm trying to polish up my projects, get rid of unnecessary dependencies and make them better and easier to receive contributions.
But I also recommend all my fellow engineers to have empathy to try to understand that there might be a bigger issue as to why maintainers might not be answering.

Best,
Gabriel

**Comment by grahamc** [comment]
:heart:
