### ISSUE TITLE
SyntaxError in Python3

### ISSUE THREAD

**Issue by jhaegg** [gabrielfalcao/HTTPretty#275]
```
File ".tox/py34/lib/python3.4/site-packages/httpretty/__init__.py", line 30, in <module>
    from .core import httpretty, httprettified, EmptyRequestHeaders
File ".tox/py34/lib/python3.4/site-packages/httpretty/core.py", line 885
    key=lambda (matcher, _): matcher.priority,
               ^
SyntaxError: invalid syntax
```

**Comment by zamiedu** [comment]
Seeing the same problem here (also happening with tox)

**Comment by jhaegg** [comment]
https://github.com/gabrielfalcao/HTTPretty/pull/276

**Comment by zachmullen** [comment]
Bump, this broke our unit tests this morning (transitive dependency via moto :)

**Comment by gabrielfalcao** [comment]
I just merged #276

**Comment by zachmullen** [comment]
Great, thanks @gabrielfalcao ... I'm assuming a patch release is forthcoming on pypi?

**Comment by gabrielfalcao** [comment]
@zachmullen actually the tests are still breaking. I am setting up my tox to try to fix it.
But I honestly don't use python3 at all, so unless someone jumps in to help, I might not be able to make a release with real python3 support

**Comment by zachmullen** [comment]
No rush or anything, thanks for looking into this. I notice the travis.yml is configured to allow failures for the py3 environment, is that because python 3 is not officially supported?

**Comment by gabrielfalcao** [comment]
yep, I'll add that to the readme
