### ISSUE TITLE
httpretty callback doesn't work with requests.Session on py2

### ISSUE THREAD

**Issue by hufman** [gabrielfalcao/HTTPretty#284]
I encountered a very strange bug in the interaction with requests.Session's use of urllib3 keepalive connection pools and httpretty with function callbacks, but only with Python 2.x. Python 3 works great!
Check out my simplest case to reproduce the issue at https://github.com/hufman/httpretty_keepalive_crash

**Comment by hufman** [comment]
When requests.Session's urllib3 tries to reuse the socket, it tries to do select.p().register(httpretty.core.sock), which fails because httpretty.core.sock doesn't have a real file handle.

**Comment by hufman** [comment]
A change that gets this working for me is provided at #285

**Comment by bhodorog** [comment]
:+1: Any news about when this one gets merged and released?

**Comment by hufman** [comment]
This was just merged
