### ISSUE TITLE
Clarity on Python 3 support?

### ISSUE THREAD

**Issue by cclauss** [gabrielfalcao/HTTPretty#300]
From README.md:

> Due to big API incompatibility between python 3.3, 3.4 and 3.5, the author of HTTPretty is not supporting python3 officially.

Is this still the case?  If so, would it be easier to drop Python 3.3 and/or Python 3.4 support in order to sidestep this "**big API incompatibility**" and just focus effort on supporting Python 2.6, 2.7, and 3.5 or higher?

https://github.com/gabrielfalcao/HTTPretty/blob/master/setup.py#L109

HTTPretty's [current PyPI record](https://pypi.python.org/pypi/httpretty) does not have a `Programming Language :: Python :: 3` classifier and that gives HTTPretty a red status on http://python3wos.appspot.com

**Comment by RSully** [comment]
Alternatively, are any forks focusing on Python 3 support? This is a great library - I'd hate to see it stuck in the past.
