### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by evan-10e** [gabrielfalcao/HTTPretty#325]
Please?

**Comment by mindflayer** [comment]
https://github.com/mindflayer/python-mocket/pull/59

**Comment by ersel** [comment]
It would be beneficial if lead developers or maintainers provided guidance on how Python 3.x could be supported. Httpretty is a great library for testing and it's a shame we can't use it with Python 3.x.

If adequate guidance is provided, maybe a contributor can undertake this work.

**Comment by mindflayer** [comment]
Mocket uses the same approach of HTTPretty and fully supports Python 3. I don't really understand what's the problem.
https://github.com/mindflayer/python-mocket/
P.S.: I am the author of Mocket.

**Comment by gabrielfalcao** [comment]
done

**Comment by evan-10e** [comment]
@gabrielfalcao thank you!
