### ISSUE TITLE
Permission denied on requires.txt

### ISSUE THREAD

**Issue by Sispheor** [gabrielfalcao/HTTPretty#338]
Seems that this file has wrong ACL in pypi.

```
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1572, in _get
with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/httpretty-0.9.4-py2.7.egg/EGG-INFO/requires.txt'
```

**Comment by Sispheor** [comment]
Actually, things are placed in EGG-INFO by pip. So it would be a pip bug?
Did you meet the issue?

**Comment by Sispheor** [comment]
Fixed?

**Comment by gabrielfalcao** [comment]
I could not reproduce and pypi seems fine.
Could you share details of how to reproduce?
Feel free to reopen

**Comment by Sispheor** [comment]
To reproduce I just declare the lib in my setup.py. 

The bug seems still present with python3

Here is the local fix I do at the end of my installation: sudo chmod -R o+r /usr/local/lib/python3.7/dist-packages/

**Comment by gabrielfalcao** [comment]
> To reproduce I just declare the lib in my setup.py.
> 
> The bug seems still present with python3
> 
> Here is the local fix I do at the end of my installation: sudo chmod -R o+r /usr/local/lib/python3.7/dist-packages/

Can you confirm this issue is not just on your machine?
HTTPretty already has several libraries that declare it as a dependency on `setup.py`:

- https://github.com/gabrielfalcao/HTTPretty/network/dependents?package_id=UGFja2FnZS01MjIwNTk5Mg%3D%3D
- https://libraries.io/pypi/httpretty/dependents

**Comment by gabrielfalcao** [comment]
> To reproduce I just declare the lib in my setup.py.
> 
> The bug seems still present with python3
> 
> Here is the local fix I do at the end of my installation: sudo chmod -R o+r /usr/local/lib/python3.7/dist-packages/

You should not install stuff to `/usr/local/` you should use virtualenv.
Sorry if I'm saying something obvious here but I'm very confused.

Perhaps if you share more details about your workflow

**Comment by Sispheor** [comment]
Hi,
On our side, the user is free to install the tool in a venv or not. But I agree with you that it's always better to use a venv when you can.

I never had the issue for other python lib so far.The lib is installed [via the setup here](https://github.com/kalliope-project/kalliope/blob/master/setup.py#L90)

The full concerned path is `dist-packages/httpretty-0.9.4-py2.7.egg/EGG-INFO/requires.txt`.
Is the `requires.txt` a file from your repo or something generated by the installer?

Thanks a lot for your help.

**Comment by Sispheor** [comment]
Ok, I just notive that I use your lib for onely one test.
I'll see how o refactor and fallback on the integrated Flask test tool.
Thanks anyway for your time !

**Comment by gabrielfalcao** [comment]
> Hi,
> On our side, the user is free to install the tool in a venv or not. But I agree with you that it's always better to use a venv when you can.
> 
> I never had the issue for other python lib so far.The lib is installed [via the setup here](https://github.com/kalliope-project/kalliope/blob/master/setup.py#L90)
> 
> The full concerned path is `dist-packages/httpretty-0.9.4-py2.7.egg/EGG-INFO/requires.txt`.
> Is the `requires.txt` a file from your repo or something generated by the installer?

https://setuptools.readthedocs.io/en/latest/formats.html#requires-txt
