### ISSUE TITLE
pycurl support

### ISSUE THREAD

**Issue by DeoLeung** [gabrielfalcao/HTTPretty#344]
Hi,

I'm trying to use this library with `pycurl` as `tornado.CurlAsyncHttpClient`, but it just simply timeout after patching, any hints on how to use it?

**Comment by dirkschneemann** [comment]
Just guessing while looking at the same problem in my code: `HTTPretty` patches Python's `socket` module. To my understanding, `pycurl`, however, accesses `libcurl` in your operating system and does not make use of `socket`, so the patch won't be used in this case.

I don't have a better solution yet though.

**Comment by gabrielfalcao** [comment]
> Just guessing while looking at the same problem in my code: `HTTPretty` patches Python's `socket` module. To my understanding, `pycurl`, however, accesses `libcurl` in your operating system and does not make use of `socket`, so the patch won't be used in this case.
> 
> I don't have a better solution yet though.

Exactly, httpretty cannot help you patch pycurl because it does not use the socket from python
