### ISSUE TITLE
Check if the registered_uri has been matched

### ISSUE THREAD

**Issue by maingoh** [gabrielfalcao/HTTPretty#350]
I would like to make sure the registered_uri have been matched during a test. I am trying to use `httpretty.latest_requests[-1].url` to check it but the `url` attribute doesn't exist in HTTPrettyRequest.

Basically I want that all the registered_uri for my test have been called. Do you have an easy way to do this ?

Thank you,

**Comment by gabrielfalcao** [comment]
you can do this with:

```python

httpretty.latest_request().url
```
