### ISSUE TITLE
Httpretty causes socket to lose connection?

### ISSUE THREAD

**Issue by f3rn4nd0-c354r** [gabrielfalcao/HTTPretty#361]
I'm using Httpretty to simulate a web API.

If I use `httpretty.enable(allow_net_connect=False)` (When allow_net_connect is False any connection to an unregistered uri will throw httpretty.errors.UnmockedError), I get an error since pymysql can't connect, via sockets, to a local DB. 

However, when I use `httpretty.enable(allow_net_connect=True)`, I get an error from a lost connection.

    ../../.virtualenvs/3.6espiga/lib/python3.6/site-packages/pymysql/__init__.py:90: in Connect
        return Connection(*args, **kwargs)
    ../../.virtualenvs/3.6espiga/lib/python3.6/site-packages/pymysql/connections.py:699: in __init__
        self.connect()
    ../../.virtualenvs/3.6espiga/lib/python3.6/site-packages/pymysql/connections.py:935: in connect
        self._get_server_information()
    ../../.virtualenvs/3.6espiga/lib/python3.6/site-packages/pymysql/connections.py:1249: in _get_server_information
        packet = self._read_packet()
    ../../.virtualenvs/3.6espiga/lib/python3.6/site-packages/pymysql/connections.py:991: in _read_packet
        packet_header = self._read_bytes(4)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    self = <pymysql.connections.Connection object at 0x7fefe1ad40f0>, num_bytes = 4
    
        def _read_bytes(self, num_bytes):
            self._sock.settimeout(self._read_timeout)
            while True:
                try:
                    data = self._rfile.read(num_bytes)
                    break
                except (IOError, OSError) as e:
                    if e.errno == errno.EINTR:
                        continue
                    self._force_close()
                    raise err.OperationalError(
                        CR.CR_SERVER_LOST,
                        "Lost connection to MySQL server during query (%s)" % (e,))
            if len(data) < num_bytes:
                self._force_close()
                raise err.OperationalError(
    >               CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
    E           pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
    
    ../../.virtualenvs/3.6espiga/lib/python3.6/site-packages/pymysql/connections.py:1037: OperationalError

How can I have Httpretty mocking the web API and leave the DB connection to run as usually?

**Comment by gabrielfalcao** [comment]
HTTPretty must be enabled *before* the connection to MySQL is created:


```python
#!/usr/bin/env python
import httpretty


import pymysql.cursors

# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='',
                             db='pymysql',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

httpretty.enable(allow_net_connect=True)
try:
    with connection.cursor() as cursor:
        # Create a new record
        sql = "INSERT INTO `users` (`email`, `password`) VALUES (%s, %s)"
        cursor.execute(sql, ('webmaster@python.org', 'very-secret'))

    # connection is not autocommit by default. So you must commit to save
    # your changes.
    connection.commit()

    with connection.cursor() as cursor:
        # Read a single record
        sql = "SELECT `id`, `password` FROM `users` WHERE `email`=%s"
        cursor.execute(sql, ('webmaster@python.org',))
        result = cursor.fetchone()
        print(result)
finally:
    connection.close()
```

**Comment by f3rn4nd0-c354r** [comment]
Hy @gabrielfalcao. Can you give me some insight on why this happens? Can't httpretty simply ignore not bound sockets/calls ?
