### ISSUE TITLE
httpretty.disable() injects pyopenssl into urllib3 even if it originally wasn't

### ISSUE THREAD

**Issue by ento** [gabrielfalcao/HTTPretty#417]
MCVE: https://gist.github.com/ento/e1e33d7d67e406bf03fe61f018404c21

Excerpt:

```sh
$ python test_httpretty_pyopenssl.py

test_without_httpretty
urllib3.util.IS_PYOPENSSL is False

test_enable_disable_httpretty
urllib3.util.IS_PYOPENSSL is True
HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

test_enable_disable_httpretty_then_extract_from_urllib3
urllib3.util.IS_PYOPENSSL is False
```

This can cause subsequent uses of the urllib3 library to fail with SSLError when the execution environment is [somehow incompatible with pyopenssl](https://github.com/pyca/pyopenssl/issues/823).

Current workaround: extract pyopenssl from urllib3 manually after calling `httpretty.disable()`:

```python
from urllib3.contrib.pyopenssl import extract_from_urllib3

extract_from_urllib3()
```

**Comment by gabrielfalcao** [comment]
Fixed in the [release `1.1.1`](https://httpretty.readthedocs.io/en/latest/changelog.html#release-1-1-1)
