### ISSUE TITLE
Should be a way to flag a registered URI as dependent on the querystring

### ISSUE THREAD

**Issue by katylava** [gabrielfalcao/HTTPretty#84]
I'd like to return a different result dependent on the querystring. Perhaps `httpretty.register_uri` could take a "use_querystring" kwarg, and pass that on until it gets to the part where it does the regex match.

For now I'm using a callable body, but that's confusing and messy for this purpose.

**Comment by mrname** [comment]
There is `match_querystring=True`:

https://github.com/gabrielfalcao/HTTPretty#matching-regular-expressions

I came here because I was having trouble with this functionality, but wanted to throw the answer up here for anybody else who needs it.

**Comment by katylava** [comment]
@mrname cool... Looks like this was added a couple months after I opened this issue (https://github.com/gabrielfalcao/HTTPretty/commit/0ac0bb493c366cbf390fe194be48b350f3226d75). Don't know why they didn't close it. Oh well, I'll close it.
